### ISSUE TITLE
[Bug] Cant Enter Edit mode

### ISSUE THREAD

**Issue by ukilop** [hazre/neosvr-mod-manager#20]
This is apparently been happening to a few of my friends as well, but simply trying to select the folder for the mods to install to,
it will just keep re-asking to select a folder. and closing it out never enters edit mode.
to be more precise: I am navigating outside the folder i want to select and clicking the folder once then hitting 'Select Folder'
friends have also tried this(even tho pretty sure this doesn't work like this): navigating inside the folder and just hitting 'Select Folder'
Maybe important note: i am trying to do the "Junction Link" method like the help says to.
 - OS: Windows 10 Version 21H2
 - Browser: Chrome
 - Chrome version: 109.0.5414.75

**Comment by ukilop** [comment]
aaaaaaaaaand that me not reading everything damit.
i was selecting the *mods* folder not the neos install folder
it works fine now...

**Comment by hazre** [comment]
Haha yeah.. it needs access to the whole Neos folder so it can also download libraries that some mods require 😅
